/**
 * Project Packager Service
 *
 * Takes generated source files and packages them into downloadable
 * ZIP archives using JSZip. Produces:
 * - Web: .zip containing a complete Next.js project
 * - Android: .apk (ZIP renamed) with full Flutter + Android project
 * - iOS: .zip with full Flutter + iOS Xcode project
 *
 * Generated by AppBuilder.
 */

import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { GeneratedFile } from '@/types/build.types';
import { TargetPlatform } from '@/types/project.types';

/* ──────────────────────────────────────────────
 * Types
 * ────────────────────────────────────────────── */

export interface PackageOptions {
  /** Target platform */
  platform: TargetPlatform;
  /** App name (used in folder / filename) */
  appName: string;
  /** App version */
  appVersion: string;
  /** Build number */
  buildNumber: number;
  /** Bundle ID */
  bundleId: string;
  /** Environment variables to include */
  envVars?: Record<string, string>;
  /** API keys to include (in .env.keys) */
  apiKeys?: Record<string, string>;
}

export interface PackageResult {
  /** Blob of the resulting file */
  blob: Blob;
  /** Suggested filename */
  filename: string;
  /** File size in bytes */
  size: number;
  /** Number of files packaged */
  fileCount: number;
  /** MIME type */
  mimeType: string;
}

/* ──────────────────────────────────────────────
 * Packager
 * ────────────────────────────────────────────── */

export class ProjectPackager {
  private zip: JSZip;
  private options: PackageOptions;
  private files: readonly GeneratedFile[];

  constructor(files: readonly GeneratedFile[], options: PackageOptions) {
    this.zip = new JSZip();
    this.options = options;
    this.files = files;
  }

  /**
   * Package all generated files into a downloadable archive.
   */
  async package(): Promise<PackageResult> {
    const safeName = this.options.appName
      .replace(/[^a-zA-Z0-9-_\s]/g, '')
      .replace(/\s+/g, '-')
      .toLowerCase();

    // Determine root folder name inside the ZIP
    const rootFolder = safeName;

    // Add all generated source files
    for (const file of this.files) {
      this.zip.file(`${rootFolder}/${file.path}`, file.content);
    }

    // Add environment files if provided
    if (this.options.envVars && Object.keys(this.options.envVars).length > 0) {
      const envContent = Object.entries(this.options.envVars)
        .map(([key, value]) => `${key}=${value}`)
        .join('\n');
      this.zip.file(`${rootFolder}/.env.local`, envContent + '\n');
    }

    if (this.options.apiKeys && Object.keys(this.options.apiKeys).length > 0) {
      const keysContent =
        '# API Keys — DO NOT COMMIT THIS FILE\n' +
        Object.entries(this.options.apiKeys)
          .map(([key, value]) => `${key}=${value}`)
          .join('\n');
      this.zip.file(`${rootFolder}/.env.keys`, keysContent + '\n');
    }

    // Platform-specific build instructions
    this.addBuildInstructions(rootFolder);

    // Generate the blob
    const { filename, mimeType } = this.getOutputInfo(safeName);
    const blob = await this.zip.generateAsync({
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 },
    });

    const fileCount = Object.keys(this.zip.files).filter(
      (f) => !this.zip.files[f].dir,
    ).length;

    return {
      blob,
      filename,
      size: blob.size,
      fileCount,
      mimeType,
    };
  }

  /**
   * Package and immediately trigger a browser download.
   */
  async packageAndDownload(): Promise<PackageResult> {
    const result = await this.package();
    saveAs(result.blob, result.filename);
    return result;
  }

  /* ──────────────────────────────────────────
   * Helpers
   * ────────────────────────────────────────── */

  private getOutputInfo(safeName: string): {
    filename: string;
    mimeType: string;
  } {
    const version = this.options.appVersion;
    const build = this.options.buildNumber;

    switch (this.options.platform) {
      case TargetPlatform.Android:
        return {
          filename: `${safeName}-v${version}-build${build}.apk`,
          mimeType: 'application/vnd.android.package-archive',
        };
      case TargetPlatform.IOS:
        return {
          filename: `${safeName}-v${version}-build${build}-ios.zip`,
          mimeType: 'application/zip',
        };
      case TargetPlatform.Web:
      default:
        return {
          filename: `${safeName}-v${version}-web.zip`,
          mimeType: 'application/zip',
        };
    }
  }

  private addBuildInstructions(rootFolder: string): void {
    switch (this.options.platform) {
      case TargetPlatform.Web:
        this.zip.file(
          `${rootFolder}/BUILD_INSTRUCTIONS.md`,
          `# Build Instructions — Web Application

## Prerequisites
- Node.js 18+ installed
- npm or yarn package manager

## Quick Start

\`\`\`bash
# Install dependencies
npm install

# Start development server
npm run dev

# Build for production
npm run build

# Start production server
npm start
\`\`\`

## Deployment

### Vercel (Recommended)
\`\`\`bash
npx vercel
\`\`\`

### Docker
\`\`\`bash
docker build -t ${rootFolder} .
docker run -p 3000:3000 ${rootFolder}
\`\`\`

### Static Export
\`\`\`bash
npm run build
# Output will be in the .next/ directory
\`\`\`

## Project Structure

\`\`\`
${rootFolder}/
├── src/
│   ├── app/          # Next.js App Router pages
│   ├── components/   # Reusable UI components
│   └── lib/          # Utilities
├── public/           # Static assets
├── package.json      # Dependencies & scripts
├── tailwind.config.js
└── tsconfig.json
\`\`\`

Generated by AppBuilder
`,
        );
        break;

      case TargetPlatform.Android:
        this.zip.file(
          `${rootFolder}/BUILD_INSTRUCTIONS.md`,
          `# Build Instructions — Android Application

## Prerequisites
- Flutter SDK 3.16+ installed
- Android Studio with Android SDK
- Java Development Kit (JDK) 17

## Quick Start

\`\`\`bash
# Get dependencies
flutter pub get

# Run on connected device/emulator
flutter run

# Build debug APK
flutter build apk --debug

# Build release APK
flutter build apk --release

# Build App Bundle (for Play Store)
flutter build appbundle --release
\`\`\`

## APK Location
After building, find your APK at:
\`\`\`
build/app/outputs/flutter-apk/app-release.apk
\`\`\`

## Signing for Release
1. Generate a keystore:
   \`\`\`bash
   keytool -genkey -v -keystore ~/key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias key
   \`\`\`
2. Create \`android/key.properties\`:
   \`\`\`
   storePassword=<password>
   keyPassword=<password>
   keyAlias=key
   storeFile=<path-to-key.jks>
   \`\`\`
3. Build: \`flutter build apk --release\`

## Project Structure

\`\`\`
${rootFolder}/
├── lib/
│   ├── main.dart         # Entry point
│   ├── app.dart          # App configuration
│   └── screens/          # Screen widgets
├── android/              # Android-specific config
│   ├── app/
│   │   ├── build.gradle
│   │   └── src/main/
│   │       ├── AndroidManifest.xml
│   │       └── kotlin/   # MainActivity
│   └── build.gradle
├── pubspec.yaml          # Dependencies
└── analysis_options.yaml
\`\`\`

Generated by AppBuilder
`,
        );
        break;

      case TargetPlatform.IOS:
        this.zip.file(
          `${rootFolder}/BUILD_INSTRUCTIONS.md`,
          `# Build Instructions — iOS Application

## Prerequisites
- macOS with Xcode 15+ installed
- Flutter SDK 3.16+ installed
- Apple Developer Account (for device deployment)
- CocoaPods (\`sudo gem install cocoapods\`)

## Quick Start

\`\`\`bash
# Get dependencies
flutter pub get

# Install iOS pods
cd ios && pod install && cd ..

# Run on iOS Simulator
flutter run -d ios

# Build for iOS (release)
flutter build ios --release

# Build IPA for distribution
flutter build ipa --release
\`\`\`

## IPA Location
After building, find your IPA at:
\`\`\`
build/ios/ipa/*.ipa
\`\`\`

## Code Signing
1. Open \`ios/Runner.xcworkspace\` in Xcode
2. Select the Runner target
3. Go to "Signing & Capabilities"
4. Select your Team
5. Xcode will manage provisioning profiles automatically

## Project Structure

\`\`\`
${rootFolder}/
├── lib/
│   ├── main.dart           # Entry point
│   ├── app.dart            # App configuration
│   └── screens/            # Screen widgets
├── ios/
│   ├── Runner/
│   │   ├── AppDelegate.swift
│   │   ├── Info.plist
│   │   └── Assets.xcassets/
│   ├── Runner.xcodeproj/
│   └── Podfile
├── pubspec.yaml            # Dependencies
└── analysis_options.yaml
\`\`\`

Generated by AppBuilder
`,
        );
        break;
    }
  }
}

/* ──────────────────────────────────────────────
 * Factory Functions
 * ────────────────────────────────────────────── */

/**
 * Package generated files and trigger a download.
 */
export async function packageAndDownload(
  files: readonly GeneratedFile[],
  options: PackageOptions,
): Promise<PackageResult> {
  const packager = new ProjectPackager(files, options);
  return packager.packageAndDownload();
}

/**
 * Package generated files into a blob (no download).
 */
export async function packageToBlob(
  files: readonly GeneratedFile[],
  options: PackageOptions,
): Promise<PackageResult> {
  const packager = new ProjectPackager(files, options);
  return packager.package();
}
