#!/usr/bin/env tsx
/**
 * AppBuilder Setup Script
 * 
 * One-command project initialization:
 *   npx tsx scripts/setup.ts
 * 
 * Steps:
 *  1. Check environment (.env file)
 *  2. Install dependencies
 *  3. Generate Prisma client
 *  4. Run database migrations
 *  5. Seed the database
 *  6. Verify setup
 */

import { execSync } from 'child_process';
import { existsSync, writeFileSync, readFileSync } from 'fs';
import path from 'path';

const ROOT = path.resolve(__dirname, '..');
const ENV_FILE = path.join(ROOT, '.env');
const DEV_DB = path.join(ROOT, 'dev.db');

// ─── Helpers ────────────────────────────────────────────────

function run(cmd: string, label: string) {
  console.log(`\n⏳ ${label}...`);
  try {
    execSync(cmd, { cwd: ROOT, stdio: 'inherit' });
    console.log(`✅ ${label} — done`);
  } catch {
    console.error(`❌ ${label} — failed`);
    process.exit(1);
  }
}

function step(label: string) {
  console.log(`\n${'─'.repeat(50)}`);
  console.log(`  ${label}`);
  console.log('─'.repeat(50));
}

// ─── Main ───────────────────────────────────────────────────

async function setup() {
  console.log('\n🚀 AppBuilder — Automated Setup\n');

  // 1. Environment
  step('1/6  Environment');
  if (!existsSync(ENV_FILE)) {
    const envContent = [
      '# AppBuilder Environment Configuration',
      '# Generated by setup script',
      '',
      '# Database',
      'DATABASE_URL="file:./dev.db"',
      '',
      '# Authentication',
      'JWT_SECRET="appbuilder-dev-secret-change-in-production"',
      'JWT_REFRESH_SECRET="appbuilder-refresh-secret-change-in-production"',
      '',
      '# Server',
      'NEXT_PUBLIC_API_URL="http://localhost:3000/api"',
      'NEXT_PUBLIC_APP_URL="http://localhost:3000"',
      '',
      '# Optional: Analytics / 3rd party',
      '# GOOGLE_ANALYTICS_ID=""',
      '# SENTRY_DSN=""',
      '',
    ].join('\n');
    writeFileSync(ENV_FILE, envContent, 'utf-8');
    console.log('✅ Created .env file with defaults');
  } else {
    // Ensure JWT_SECRET exists
    const envContent = readFileSync(ENV_FILE, 'utf-8');
    const additions: string[] = [];
    if (!envContent.includes('JWT_SECRET')) {
      additions.push('JWT_SECRET="appbuilder-dev-secret-change-in-production"');
    }
    if (!envContent.includes('NEXT_PUBLIC_API_URL')) {
      additions.push('NEXT_PUBLIC_API_URL="http://localhost:3000/api"');
    }
    if (additions.length > 0) {
      writeFileSync(ENV_FILE, envContent + '\n' + additions.join('\n') + '\n', 'utf-8');
      console.log(`✅ Added missing env variables: ${additions.length}`);
    } else {
      console.log('✅ .env file exists and looks good');
    }
  }

  // 2. Dependencies
  step('2/6  Dependencies');
  run('npm install', 'Installing packages');

  // 3. Prisma Client
  step('3/6  Prisma Client');
  run('npx prisma generate', 'Generating Prisma client');

  // 4. Database Migrations
  step('4/6  Database Migrations');
  if (existsSync(DEV_DB)) {
    console.log('ℹ️  Database already exists, running pending migrations...');
    run('npx prisma migrate deploy', 'Applying migrations');
  } else {
    run('npx prisma migrate dev --name init', 'Creating database & running migration');
  }

  // 5. Seed
  step('5/6  Seed Data');
  run('npx tsx prisma/seed.ts', 'Seeding database');

  // 6. Verify
  step('6/6  Verification');
  
  const checks = [
    { label: 'node_modules', path: path.join(ROOT, 'node_modules') },
    { label: '.env', path: ENV_FILE },
    { label: 'dev.db', path: DEV_DB },
    { label: 'Prisma client', path: path.join(ROOT, 'node_modules', '@prisma', 'client') },
    { label: 'prisma/migrations', path: path.join(ROOT, 'prisma', 'migrations') },
  ];

  let allGood = true;
  for (const check of checks) {
    if (existsSync(check.path)) {
      console.log(`  ✅ ${check.label}`);
    } else {
      console.log(`  ❌ ${check.label} — missing`);
      allGood = false;
    }
  }

  if (allGood) {
    console.log('\n' + '═'.repeat(50));
    console.log('  🎉 Setup complete! Run the app with:');
    console.log('     npm run dev');
    console.log('');
    console.log('  📧 Default credentials:');
    console.log('     Admin:  admin@appbuilder.dev / Admin@123');
    console.log('     Demo:   demo@appbuilder.dev  / Demo@123');
    console.log('');
    console.log('  📡 API:    http://localhost:3000/api/health');
    console.log('  🎨 App:    http://localhost:3000/builder');
    console.log('  🗃️  Studio: npm run db:studio');
    console.log('═'.repeat(50) + '\n');
  } else {
    console.error('\n⚠️  Some checks failed. Review output above.\n');
    process.exit(1);
  }
}

setup().catch((err) => {
  console.error('Setup failed:', err);
  process.exit(1);
});
